### ISSUE TITLE
Create releases with executables for Windows and Linux

### ISSUE THREAD

**Issue by gamesbook** [mdhender/wow#1]
For those of us without Go installed, is it possible for you to release executable versions of the programme (say for Windows and Linux); e.g. as per:

https://www.digitalocean.com/community/tutorials/how-to-build-go-executables-for-multiple-platforms-on-ubuntu-20-04

**Comment by mdhender** [comment]
Updated title. Created a better server and installed it on digital ocean. Posted the URL to the warp wars group.

**Comment by mdhender** [comment]
@gamesbook - will https://groups.io/g/warpwar/message/3342 work for you?

**Comment by mdhender** [comment]
If that doesn't, I can build releases. Just have to decide how and where to store them. I don't like putting binaries in git.

**Comment by gamesbook** [comment]
Looks fine to me.  Will you add the direct link (https://wraith.dev/wow/) to the readme?
